### ISSUE TITLE
File size

### ISSUE THREAD

**Issue by Veranep** [Veranep/TMCI_Kamiel_Baran_Vera#1]
The size of our data file is too big to be read in using the translate-toolkit reader for .tmx files. It raises an error saying there is no more memory locations that can be allocated.

**Comment by AlricRahl** [comment]
https://stackoverflow.com/questions/17056382/read-file-in-chunks-ram-usage-read-strings-from-binary-files
This link might help us with the size issue, will look into it further

**Comment by Giovanni1085** [comment]
How are you doing here? I recommend looking into streaming instead of reading. See e.g., https://docs.python.org/3/library/io.html

**Comment by AlricRahl** [comment]
We fixed it by using the basic stream that goes like
`f = open("data.txt", "r")`
This enabled us to read it chunk by chunk, and we decided to have chunks of roughly half a gigabyte. We now have a pickle with just the line pairs(english and dutch of same sentence) in a list.
