### ISSUE TITLE
Update 1

### ISSUE THREAD

**Issue by Veranep** [Veranep/TMCI_Kamiel_Baran_Vera#2]
- Kamiel read and explained to us the pytorch implementation of sequence to sequence neural networks. We have decided to use the main structure of this implementation, but experiment with meaningful changes and extra features, and possibly combine these, to find the best model.  

- Baran finished the preprocessing, which can be found in the 'preprocessing_notebook.ipynb' iPython notebook, up to the point that we have a pickled file that contains all sentence pairs. This preprocessed data is ready to be made into a small training data set to use to find the best model.

- Vera read and summarized papers on translation models, for which details and the summaries can be found in the Wiki of this repository. She explained to us some different features and evaluation standards that were introduced by the different papers, and that we might be able to use.

More information on what we want to finish for Update 2 can be found in Milestone 'Update 2'.

**Comment by Giovanni1085** [comment]
Which PyTorch tutorial are you using at the moment?

**Comment by Veranep** [comment]
[This one](https://pytorch.org/tutorials/intermediate/seq2seq_translation_tutorial.html), the same one we showed you in class last week.
